Replace mockito-inline with mockito-inline to workaround Java 16's enforcement of encapsulation.
java.lang.NullPointerException: Cannot enter synchronized block because
"this.lock" is null.

See https://github.com/mockito/mockito/issues/2164